[project]
name = "parallel-llama-df-analysis"
version = "0.0.1"
description = "Async Ollama helpers for analysis of documents stored in a datafrae."
authors = [{name = "Quido Haškovec"}]
requires-python = ">=3.9"
dependencies = ["pandas", "numpy", "tqdm", "ollama", "nest_asyncio"]
