# .github/workflows/publish.yml
name: Build & publish to PyPI

on:
  push:
    tags: ["v*"]                # e.g. git tag v0.1.0 && git push origin v0.1.0

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:                # needed for reading repo contents
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Build wheel & sdist
      run: |
        python -m pip install --upgrade build
        python -m build          # creates dist/*.whl  and  dist/*.tar.gz


    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository_url: https://test.pypi.org/legacy/
        username: __token__
        password: ${{ secrets.TEST_PYPI_API }}

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        username: __token__
        password: ${{ secrets.PYPI_API }}
